apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: private-quarkus-devfile-sample-jmoc
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hoyr-tenant/private-devfile/private-quarkus-devfile-sample-jmoc@sha256:8416318137f092c6a52f759749f034fdcb0b96a2e69f9ad901fd2f8ca2a9735a
        name: my-java-quarkus
        resources: {}
status: {}
