apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: private-quarkus-devfile-sample-jmoc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: private-quarkus-devfile-sample-jmoc
    app.kubernetes.io/part-of: private-devfile
  name: private-quarkus-devfile-sample-jmoc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: private-quarkus-devfile-sample-jmoc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: private-quarkus-devfile-sample-jmoc
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hoyr-tenant/private-devfile/private-quarkus-devfile-sample-jmoc@sha256:8416318137f092c6a52f759749f034fdcb0b96a2e69f9ad901fd2f8ca2a9735a
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
